version: '3'

services:
    mongodb:
        image: mongo:4
        volumes:
            - /usr/lib/mongo
        ports: 
            - "27017:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin            
    
    postgres:
        image: postgres
        ports: 
            - "5432:5432"
        volumes:
            - /usr/lib/postgres
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin            
        